version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017
    networks:
      - back
  api:
    build: ./server
    volumes:
      - ./server/api:/srv/app/api
    ports:
      - 3004:3004
    networks:
      - front
      - back
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - mongo
  seed:
    build:
      context: ./server
      dockerfile: Dockerfile-seed
    volumes:
      - ./server/api:/srv/app/api
    networks:
      - back
    depends_on:
      - mongo

networks:
  front:
    driver: bridge
  back:
    driver: bridge
